---
require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/ClassLength:
  Max: 400

Style/IfUnlessModifier:
  Enabled: false # because it wants to make lines >80 chars
Style/StringConcatenation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false

# Is nothing sacred?
Layout/LineLength:
  Max: 80
