---

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringConcatenation:
  Enabled: false

# Allow long blocks of tests
#
Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

Metrics/AbcSize:
  Max: 80
