---

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Allow long blocks of tests
#
Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

Metrics/AbcSize:
  Max: 80
