name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  rubygems:
    name: Build and Publish to Rubygems
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >>$GITHUB_ENV

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - run: bundle install

    - name: Run tests
      run: bundle exec rake

    - name: Build Gem
      run: bundle exec rake build

    - name: Publish to RubyGems
      run: |
        mkdir -p ${HOME}/.gem
        echo -e "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}" >${HOME}/.gem/credentials
        chmod 0600 ${HOME}/.gem/credentials
        gem push pkg/*.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

  docker-hub:
    name: Build and Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >>$GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Github Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          snltd/meetup-generator
        tags: |
          type=semver,pattern={{version}}

    - name: Build and Push Docker Container
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
   
