name: Build and Release to Docker Hub

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-hub:
    name: Build and Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >>$GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Github Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          snltd/meetup-generator
        tags: |
          type=semver,pattern={{version}}

    - name: Build and Push Docker Container
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
   
