name: Build and Release to Rubygems

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  rubygems:
    name: Build and Publish to Rubygems
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >>$GITHUB_ENV

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - run: bundle install

    - name: Run tests
      run: bundle exec rake

    - name: Build Gem
      run: bundle exec rake build

    - name: Publish to RubyGems
      run: |
        mkdir -p ${HOME}/.gem
        echo -e "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}" >${HOME}/.gem/credentials
        chmod 0600 ${HOME}/.gem/credentials
        gem push pkg/*.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
